modLoader="javafml"
loaderVersion="[4,)"
license="\u00A79Rocky Studios Inc"

[[mods]]
modId="rockylib"
version="2.2.485"
displayName="RockyLib"
updateJSONURL="https://www.github.com/RockyyyFOG/The-Tools-And-Other"
displayURL="https://www.rockystudiosllc.blogspot.com/"
credits="\"\""
authors="RockyyyFOG"
description="Library For The Mods"
displayTest="IGNORE_SERVER_VERSION"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.rockylib]]
    modId="neoforge"
    type="required"
    versionRange="[21.4.123,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.rockylib]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.4]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration